#!/bin/bash

if [[ -e /etc/lsb-release ]]; then
  . /etc/lsb-release
  if [[ ! -z $DISTRIB_ID ]]; then
    PLATFORM_DISTRO="${DISTRIB_ID}"
  fi
fi

if [[ `uname -a ` =~ "Microsoft" ]]; then
  export PLATFORM="WSL"
  export PLATFORM_SCRIPT=~/.wsl_zshrc
elif [[ `uname -a ` =~ "microsoft" ]]; then
  export PLATFORM="WSL2"
  export PLATFORM_SCRIPT=~/.wsl_zshrc
elif [[ `uname -a ` =~ "Darwin" ]]; then
  export PLATFORM="OSX"
  export PLATFORM_SCRIPT=~/.osx_zshrc
elif [[ `uname -a ` =~ "Linux" ]]; then
  export PLATFORM="LINUX"
  export PLATFORM_SCRIPT=~/.linux_zshrc
else
  export PLATFORM="CYGWIN"
  export PLATFORM_SCRIPT=~/.pc_zshrc
fi

if [[ ${PLATFORM} -eq "WSL" || ${PLATFORM} -eq "WSL2" || ${PLATFORM} -eq  "CYGWIN"  \
      && -e ~/.ssh_port_forwarding ]]; then
  . ~/.ssh_port_forwarding
else
  SSH_PORT_FWD=""
fi

