#!/bin/bash

if [[ -e /etc/lsb-release ]]; then
  . /etc/lsb-release
  if [[ ! -z $DISTRIB_ID ]]; then
    PLATFORM_DISTRO="${DISTRIB_ID}"
  fi
  if [[ -d ~/.local/${DISTRIB_RELEASE} ]]; then
    export PATH=~/.local/${DISTRIB_RELEASE}/bin:$PATH
    export LD_LIBRARY_PATH=~/.local/${DISTRIB_RELEASE}/lib:$LD_LIBRARY_PATH
    export MANPATH=~/.local/lib/${DISTRIB_RELEASE}/man:$MANPATH
  fi
fi

export PLATFORM=UNK

if [ -e ${HOME}/scripts/platform.sh ]; then
   source ${HOME}/scripts/platform.sh
   export PLATFORM=$(get_platform)
fi

case $PLATFORM in
   WSL||WSL2)
      export PLATFORM_SCRIPT=~/.wsl_zshrc
      ;;
   OSX)
      export PLATFORM_SCRIPT=~/.osx_zshrc
      ;;
   LINUX)
      export PLATFORM_SCRIPT=~/.linux_zshrc
      ;;
   CYGWIN)
      export PLATFORM_SCRIPT=~/.pc_zshrc
      ;;
esac

if [[ ${PLATFORM} -eq "WSL" || ${PLATFORM} -eq "WSL2" || ${PLATFORM} -eq  "CYGWIN"  \
      && -e ~/.ssh_port_forwarding ]]; then
  . ~/.ssh_port_forwarding
else
  SSH_PORT_FWD=""
fi

