#!/bin/bash

LOGFILE=/tmp/livestream.log

ipaddr="localhost"
user="admin"
password="admin"

options=$(getopt -o i:p:u: -- "$@")
[ $? -eq 0 ] || {
  echo "Incorrect options provided"
  exit 1
}
eval set -- "$options"

while true; do
    case "$1" in
    -i)  shift; ipaddr=$1 ;;
    -u)  shift; user=$1 ;;
    -p)  shift; password=$1 ;;
    --) shift; break ;;
    *) echo "Internal error"; exit 1 ;;
    esac
    shift
done

OPTIONS="-I rc --rc-host localhost:4212 --fullscreen rtsp://$user:$password@$ipaddr"
DEST="rtsp://$user:$password@$ipaddr"

found=`ps ax | grep $ipaddr | grep -v run_live_stream | grep -v grep`
if [[ -z $found ]]; then
  echo "========================================================================" >> $LOGFILE
  echo "running live stream at " `date` >> $LOGFILE
  DISPLAY=:0 vlc ${OPTIONS} ${DEST} &>> $LOGFILE &
else
  percent_cpu=`ps -eo cmd,%cpu | grep vlc | grep -v grep | cut -d" " -f 6`
  echo ${percent_cpu}
  off=`echo ${percent_cpu}'<'20.0 | bc -l`
  if [ $off -eq 1 ]; then
    pkill vlc
    echo "========================================================================" >> $LOGFILE
    echo "running live stream at " `date` >> $LOGFILE
    DISPLAY=:0 vlc ${OPTIONS} ${DEST} &>> $LOGFILE &
  fi
fi
